### Get comments by media id
GET http://localhost:3000/api/comments/media/60

### Get comments by user id
GET http://localhost:3000/api/comments/user/10

### Post a comment

POST http://localhost:3000/api/comments
Content-Type: application/json

{
    "media_id": 19,
    "user_id": 16,
    "comment_text": "Beautiful cat!"
}

### Post a comment FAIL

POST http://localhost:3000/api/comments
Content-Type: application/json

{
    "media_id": 19,
    "comment_text": "Beautiful cat!"
}

### Update a comment

PUT http://localhost:3000/api/comments/1
Content-Type: application/json

{
    "comment_text": "This is an updated comment"
}

### Delete a comment

DELETE http://localhost:3000/api/comments/11
